/**
 * Career profile read/write operations.
 *
 * The profile is written once by /papyrus-setup and read by every other skill.
 * It lives at {configDir}/profile.md as markdown with YAML frontmatter.
 *
 * All skill personalization — journal question depth, career document framing,
 * coaching tone — is driven by the values in this file.
 */

import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { PATHS } from './paths.js';

// ─── Types ──────────────────────────────────────────────────────────────────

export type Level = 'junior' | 'mid' | 'senior' | 'staff';
export type Goal = 'promotion' | 'job_search' | 'growth' | 'unsure';
export type YearsAtLevel = 'under_1' | 'one_to_two' | 'over_2';
export type CompanyType = 'big_tech' | 'mid_size' | 'startup' | 'freelance';
export type Domain = 'backend' | 'frontend' | 'infra' | 'ml' | 'fullstack';
export type StaffArchetype = 'tech_lead' | 'architect' | 'solver' | 'right_hand' | null;

export interface Profile {
  level: Level;
  goal: Goal;
  years_at_level: YearsAtLevel;
  company_type: CompanyType;
  domain: Domain;
  staff_archetype: StaffArchetype;
  created_at: string;  // YYYY-MM-DD
  updated_at: string;  // YYYY-MM-DD
}

export type ProfileInput = Omit<Profile, 'created_at' | 'updated_at'>;

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Read the career profile. Returns null if /papyrus-setup has not been run.
 */
export function readProfile(profilePath: string = PATHS.profilePath): Profile | null {
  if (!fs.existsSync(profilePath)) return null;

  const raw = fs.readFileSync(profilePath, 'utf-8');
  const { data } = matter(raw);
  return data as Profile;
}

/**
 * Write or update the career profile.
 * Preserves created_at if a profile already exists.
 */
export function writeProfile(
  input: ProfileInput,
  profilePath: string = PATHS.profilePath,
): void {
  const dir = path.dirname(profilePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }

  const today = new Date().toISOString().split('T')[0];
  const existing = readProfile(profilePath);

  const data: Profile = {
    ...input,
    created_at: existing?.created_at ?? today,
    updated_at: today,
  };

  const body = [
    '# My Papyrus Profile',
    '',
    'Generated by /papyrus-setup. Re-run that skill to update.',
  ].join('\n');

  fs.writeFileSync(profilePath, matter.stringify(body, data), 'utf-8');
}

/**
 * Check whether the profile exists (i.e. /papyrus-setup has been run).
 */
export function profileExists(profilePath: string = PATHS.profilePath): boolean {
  return fs.existsSync(profilePath);
}

// ─── CLI entry point ─────────────────────────────────────────────────────────
// Skills call this file directly to read or write the profile.
//
// Usage:
//   npx tsx src/lib/profile.ts read
//   npx tsx src/lib/profile.ts exists

if (process.argv[1] === new URL(import.meta.url).pathname) {
  const [, , command, ...args] = process.argv;

  switch (command) {
    case 'read': {
      const profile = readProfile();
      if (!profile) { process.stderr.write('No profile found. Run /papyrus-setup first.\n'); process.exit(1); }
      process.stdout.write(JSON.stringify(profile, null, 2) + '\n');
      break;
    }

    case 'exists':
      process.stdout.write(JSON.stringify({ exists: profileExists() }) + '\n');
      break;

    case 'write': {
      const raw = args[0];
      if (!raw) { process.stderr.write('Usage: profile.ts write \'{"level":"senior",...}\'\n'); process.exit(1); }
      let input: ProfileInput;
      try {
        input = JSON.parse(raw) as ProfileInput;
      } catch {
        process.stderr.write('Invalid JSON input\n'); process.exit(1);
      }
      writeProfile(input!);
      process.stdout.write(JSON.stringify({ ok: true }) + '\n');
      break;
    }

    default:
      process.stderr.write('Usage: profile.ts read | exists | write <json>\n');
      process.exit(1);
  }
}
